### ISSUE TITLE
"MSI Application not found or version not supported" 

### ISSUE THREAD

**Issue by glanzgurke** [fischmat/mysticlight4j#11]
I was giving this project my first try and tried to use your example given in your readme to fetch my devices, but with both the object oriented and low-level api the error:

> Exception in thread "main" de.matthiasfisch.mysticlight4j.api.MysticLightAPIException: MSI Application not found or installed version not supported.
> 	at de.matthiasfisch.mysticlight4j.api.MysticLightNativeBinding.initialize(Native Method)
> 	at de.matthiasfisch.mysticlight4j.api.MysticLightAPI.initialize(MysticLightAPI.java:80)
> 	at de.matthiasfisch.mysticlight4j.api.MysticLightAPI.initialize(MysticLightAPI.java:60)
> 	at de.matthiasfisch.mysticlight4j.MysticLight4j.<init>(MysticLight4j.java:54)
> 	at de.matthiasfisch.mysticlight4j.MysticLight4j.<init>(MysticLight4j.java:32)

 occured while initializing the msi api. my mystic light sdk is present so i assume it may have something to do with the version? i would appreciate your help and if you need any logs or something i can of course send them to you. 
thank you in advance.

**Comment by coachpo** [comment]
same issue
